// ...existing code...
                    <x-nav-link :href="route('restaurant-status.index')" :active="request()->routeIs('restaurant-status.index')">
                        {{ __('Restaurant Status') }}
                    </x-nav-link>
// ...existing code...
